# Generated by Django 4.2.4 on 2023-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('is_admitted', models.BooleanField(default=True)),
                ('fees', models.IntegerField()),
                ('admitted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinqueries.college')),
            ],
        ),
    ]
