# Generated by Django 4.2.4 on 2023-09-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinqueries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='test@abc.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_admitted',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.TextField(max_length=100),
        ),
    ]
