# Generated by Django 4.2.4 on 2023-09-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinqueries', '0002_student_email_id_alter_student_is_admitted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_admitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
    ]
