# Generated by Django 4.2.4 on 2023-09-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joinqueries', '0003_remove_student_email_id_alter_student_is_admitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admitted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_ad', to='joinqueries.college'),
        ),
    ]
