# Generated by Django 4.2.4 on 2023-09-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_reference', models.CharField(max_length=25)),
                ('period', models.DateField()),
                ('data_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=1)),
                ('units', models.CharField(max_length=25)),
                ('magnitude', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
