# Generated by Django 4.2.4 on 2023-09-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bizdata',
            name='data_value',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bizdata',
            name='magnitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bizdata',
            name='period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bizdata',
            name='series_reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bizdata',
            name='units',
            field=models.CharField(max_length=50),
        ),
    ]
