# Generated by Django 4.2.4 on 2023-08-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documents_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='upload_date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
